Dues screen added
HackSlashNITP/LibraLink pull request #13
Opened 2023-10-29 08:03 UTC by mahimak13

@RitwikSingh28 Sir I have added dues screen page.  kindly review it. 
![Screenshot 2023-10-29 133216](https://github.com/HackSlashNITP/LibraLink/assets/130887188/3d0fadb9-7420-4792-8cd8-646126a66808)

2023-10-29 11:19 UTC, RitwikSingh28 commented on lib/main.dart
> +      home: Scaffold(body: DuesScreen()),
Please reset the `home` to `LandingPage`

2023-10-29 11:22 UTC, RitwikSingh28 requested changes
Good work @mahimak13
Please make the one change that I have mentioned in the preceding comment, resolve that and then we are good to go with your work

2023-10-29 14:05 UTC, mahimak13 commented
> Good work @mahimak13 Please make the one change that I have mentioned in the preceding comment, resolve that and then we are good to go with your work

Sir I have resolved the changes and have also added no dues page. Kindly review the changes
![image](https://github.com/HackSlashNITP/LibraLink/assets/130887188/68cfcd72-5a94-49c7-870b-c8230522e407)

2023-10-30 03:41 UTC, RitwikSingh28 approved these changes
Great work @mahimak13

2023-10-30 03:41 UTC, merged