HomePage added
HackSlashNITP/LibraLink pull request #15
Opened 2023-10-29 16:49 UTC by Jayvashishtha123

Homepage created.....

https://github.com/HackSlashNITP/LibraLink/assets/132293279/ca8e7f94-efef-47db-ade7-35abb3c1f65d

![Screenshot_1698597712](https://github.com/HackSlashNITP/LibraLink/assets/132293279/91e69645-feab-4ea6-8620-3ec31eb1e9a4)
![Screenshot_1698597766](https://github.com/HackSlashNITP/LibraLink/assets/132293279/3506bbc0-cf0d-4901-9cb4-167066f3a485)

![Screenshot_1698597745](https://github.com/HackSlashNITP/LibraLink/assets/132293279/53f7aa45-7f84-42de-8aa5-024f995516b2)

2023-10-31 00:55 UTC, RitwikSingh28 requested changes
@Jayvashishtha123 
Splendid work. The page looks great and neat.
Just make one little change and we will be okay to merge your work

2023-10-31 00:55 UTC, RitwikSingh28 commented on lib/main.dart
> +      home: HomePage(),
Change the `home` property to `LandingPage` to show it by default

2023-11-07 05:28 UTC, ShubhamTiwari55 reviewed
@Jayvashishtha123 Solve your merge conflicts and then inform me so that I can merge your PR

2023-11-07 08:50 UTC, ShubhamTiwari55 approved these changes
Good work @Jayvashishtha123 Merging this PR

2023-11-07 08:51 UTC, merged